version: '3'
services:

  localstack:
    container_name: devtalk
    hostname: devtalk
    image: localstack/localstack
    ports:
      - "4566-4584:4566-4584"
      - "1010:8080"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI-9091}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./aws:/docker-entrypoint-initaws.d